name: Build-and-Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    env:
      configuration: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.configuration }}
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration ${{ env.configuration }}
